[ Style ] 사이드바 공통 컴포넌트 구현
DOTOREAD/DOTOREAD-CLIENT pull request #10
Opened 2024-09-30 18:09 UTC by qkrcodus

## 🔥 Related Issues

- close #9 

## ✅ 작업 리스트

- [ ] 사이드바 공통 컴포넌트 구현
- [ ] 메뉴 클릭시 다른 svg 컴포넌트 렌더링

## 🔧 작업 내용

### theme.ts
```
Pretendard_Bold_20px: css`
	${baseFontStyle}
	font-size: 20px;
	font-weight: 700;
`,
```
사이드바 하단 5/20 해당하는 폰트를 추가하였습니다.

### Roots.tsx
```
import Header from './components/common/Header/Header';
import SideBar from './components/common/SideBar/SideBar';
import { Outlet } from 'react-router-dom';

function Roots() {
	return (
		<>
			<Header />
			<SideBar />
			<Outlet />
		</>
	);
}
export default Roots;
```
`Roots.tsx`에 Outlet 세팅해서 `Header`와 `SideBar` 컴포넌트를 default로 화면에 띄워줄 수 있게 하였습니다.

### SideBar.tsx
```
interface Icon {
	id: string;
	default: React.ElementType;
	clicked: React.ElementType;
}

const icons: Icon[] = [
	{ id: 'home', default: HomeIcon, clicked: HomeIconClicked },
	{ id: 'bookmark', default: BookMarkIcon, clicked: BookMarkIconClicked },
	{ id: 'share', default: ShareIcon, clicked: ShareIconClicked },
	{ id: 'mission', default: MissionIcon, clicked: MissionIconclicked },
	{ id: 'mypage', default: MyPageIcon, clicked: MyPageIconClicked },
];

function SideBar() {
	const [clicked, setClicked] = useState<string>('home');
	return (
		<SideBarWrapper>
			<Menus>
				{icons.map((icon) => (
					<Icon
						key={icon.id}
						as={clicked === icon.id ? icon.clicked : icon.default}
						onClick={() => setClicked(icon.id)}
					/>
				))}
			</Menus>
			<StorageWrapper>
				<Acorn />
				<StorageCount>5/20</StorageCount>
			</StorageWrapper>
		</SideBarWrapper>
	);
}

export default SideBar;

```
클릭했을때 보이는 svg 파일까지 모두 컴포넌트로 만들어 넣어뒀습니다.
`Icon`이라는 이름의 인터페이스를 정의하여 이를 자료형으로 사용할 수 있게 했습니다.
`clicked` 변수에 'home'을 넣어둬 클릭된 홈 아이콘이 default로 뜨게 하였습니다.
클릭 이벤트틀 정의하였습니다.

## 🧐 새로 알게된 점
### as prop
 컴포넌트가 어떤 타입의 요소로 렌더링될지 지정할 수 있는 prop이다.
```
<Icon
	key={icon.id}
        as={clicked === icon.id ? icon.clicked : icon.default}
        onClick={() => setClicked(icon.id)} 
/>
```
### 중첩 라우팅을 위한 outlet
자식 라우트들의 렌더링 위치를 지정한다.
```
export const router = createBrowserRouter([
	{
		path: '',
		element: <Roots />,
		children: [
			{
				path: '/',
				element: <MainPage />,
			},
		],
	},
]);
```
```
function Roots() {
	return (
		<>
			<Header />
			<SideBar />
			<Outlet />
		</>
	);
}
```

## 🤔 궁금한 점

## 📸 스크린샷 / GIF / Link

https://github.com/user-attachments/assets/4503ca7e-04e6-4dda-80c7-a4ebc6a9bbff

2024-10-01 17:03 UTC, KIMGEONHWI requested changes
고생하셨어요!

2024-10-01 17:03 UTC, KIMGEONHWI commented on src/components/common/SideBar/SideBar.tsx
> +];
```icons``` 배열을 상수배열이므로 ```constants``` 폴더로 분리하는 것이 좋을 것 같습니다.
```constants/icons.ts```에 분리해서 사용해주세요.

2024-10-01 17:03 UTC, KIMGEONHWI commented on src/components/common/SideBar/SideBar.tsx
> +];
현재 ```constants``` 폴더가 없으므로 생성해서 사용해주세요!

2024-10-01 17:03 UTC, KIMGEONHWI commented on src/components/common/SideBar/SideBar.tsx
> +			</StorageWrapper>
```Acorn```과 ```StorageCount```가 다른 곳에서도 사용될 가능성이 있으므로 ```components/Storage.tsx``` 로 분리해서 사용하는 것은 어떨까요?

```5/20```부분도 하드 코딩 보다는
```typescript
export function Storage({ current, total }: { current: number, total: number }) {
  return (
    <StorageWrapper>
      <Acorn />
      <StorageCount>{current} / {total}</StorageCount>
    </StorageWrapper>
  );
}
```
사용하는 부분
```typescript
 <Storage current="5" total="20" />
```
와 같이 Props로 넘겨서 사용할 수 있도록 하는 것은 어떨까요?

2024-10-02 04:36 UTC, qkrcodus commented on src/components/common/SideBar/SideBar.tsx
> +			</StorageWrapper>
오호 감사합니다!

2024-10-02 05:23 UTC, merged